const mongoose = require("mongoose");

const StudentSchema = new mongoose.Schema({
    registerNum: { type: String, unique: true }, // Random KNSxxxxx, unique
    firstname: { type: String, required: true },
    middlename: String,
    lastname: { type: String, required: true },
    extension: String,
    birthdate: String,
    phone: String,
    register: String, // optional, NOT unique
    email: { type: String, required: true, unique: true, lowercase: true, trim: true },
    password: { type: String, required: true },
    conpassword: String,
    studentNumber: { type: String, default: null },
    domainEmail: { type: String, default: null },
    portalPassword: { type: String, default: null },

    idimage: String,
    birthCertImage: String,
    goodMoralImage: String,
    academic: String,
    image: String,

    validId: { type: String, default: '❌' },
    birthCert: { type: String, default: '❌' },
    goodMoral: { type: String, default: '❌' },
    academicImage: { type: String, default: "" },
    profileImage: { type: String, default: '❌' },

    birthplace: String,
    civil: String,
    sex: String,
    citizenship: String,
    religion: String,
    region: String,
    province: String,
    city: String,
    barangay: String,
    disability: String,
    disabilityCategory: String,
    disabilityDetails: String,

    selectedCourse: String,
    selectedSecCourse: String,
    initialDept: String,
    scholar: String,
    otherScholar: String,
    elementary: String,
    elemYear: String,
    highschool: String,
    highYear: String,
    schoolType: String,
    strand: String,
    lrn: String,
    honor: String,
    college: String,
    technical: String,
    certificate: String,
    course: String,
    year: String,
    program: String,
    yearCom: String,
    achivements: String,

    fatName: String,
    fatMidName: String,
    fatLastName: String,
    fatExt: String,
    motName: String,
    motMidName: String,
    motLastName: String,
    broNum: String,
    sisNum: String,
    guarName: String,
    guarRelationship: String,
    guarAddress: String,
    guarEmail: String,
    guarTel: String,

    studentyear: String,
    isAccepted: { type: Boolean, default: false }
}, { timestamps: true });

const StudentModel = mongoose.model("students", StudentSchema);
module.exports = StudentModel;
